name: Clean Storage
description: Remove Unnecessary Storage
runs:
  using: composite
  steps:
    - run: |
        df -h
        echo "+++++++++++"
        sudo rm -rf /usr/share/dotnet \
          /usr/local/lib/android \
          /usr/local/share/android-sdk \
          /usr/share/swift \
          /opt/hostedtoolcache/CodeQL \
          /opt/hostedtoolcache/* \
          /opt/ghc
        
        docker image prune --all --force
        docker builder prune -a

        # apt
        sudo apt-get remove -y \
            firefox chromium-browser \
            ruby php nodejs
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        
        echo "+++++++++++"
        df -h
      shell: bash
