channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.12
  - jupyterlab==4.3.6
  - jupyterhub==5.2.1
  - notebook==7.3.3
  - ipykernel
  - ipywidgets
  - jupytext
  - nbgitpuller
  - dask
  - dask-labextension
  - numpy
  - scipy
  - pandas
  - astropy
  - pyvo
  - astroquery
  - tqdm
  - matplotlib
  - seaborn
  - pytest
  - code-server
  - pip
  - pip:
      - ipykernel
      - ipywidgets
      - jupytext
      - jupyterlab_execute_time
      - jupyter-resource-usage
      - jupyterlab-git
      - jupyterlab-myst
      - jupyter-vscode-proxy
      - jupyter_cpu_alive
      - jupyter-vscode-proxy
