channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.11
  - jupyterlab
  - jupytext
  - dask
  - dask-labextension
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - astropy
  - astropy-healpix
  - ccdproc
  - photutils
  - regions
  - reproject
  - specutils
  - pyvo
  - astroquery
  - statsmodels
  - tqdm
  - seaborn
  - pip
  - pip:
      - specreduce
      - jupyterlab-git
      - jupyterlab-myst
      - jupyterlab-bxplorer
      - jupyterlab-s3-browser
      