#!/bin/bash
# Handle uv environment
# Creates an environment for every requirements-{env-name}.txt file

# exit on failure
set -e
set -o pipefail

echo
echo "  Setup pip-based python environment using uv, along with the notebook kernel."
echo "  For help, see: $0 -h"
echo

# emvdir: where to install the new environment
# if not given, default to ENV_DIR
arg=$1
if [ -z $arg ]; then
    envdir=$ENV_DIR

elif [[ "$arg" == "--user" ]]; then
    envdir=$USER_ENV_DIR

elif [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
    echo """

    USAGE:
    -----

      1. Create a standard requirements text file named: requirements-{env_name}.txt.
    Where {env_name} is the name of your environment.
    
      2. Call 'setup-pip-env [--user]' to create the environment and setup the kernel.
    By default, the new environment will be created in \$ENV_DIR, which is reset with a new session.
    Pass --user to install in \$USER_ENV_DIR (default to ~/user-envs) that persists between sessions.
    
    Activate with: source \$ENV_DIR/{env_name}/bin/activate 
        (or source \$USER_ENV_DIR/{env_name}/bin/activate if you passed --user)
"""
    exit 0
else
    echo "Unknown argument $1"
    exit 1
fi

# check if we have files
shopt -s nullglob
files=( requirements-*.txt )
if (( ${#files[@]} > 0 )); then
    echo "Found ${#files[@]} files:"
    printf "  %s\n" "${files[@]}"
    read -r -p "Continue? [y/N] " ans
    case "$ans" in
        [Yy]*) echo "Installing environment in: $envdir";;
        *)     exit 0;;
    esac 
else
    echo "No requirements-*.txt files found; see setup-pip-env -h"
    exit 0
fi


for envfile in ${files[@]}; do
    env=`echo $envfile | sed -n 's/requirements-\(.*\)\.txt/\1/p'`
    if test -f requirements-${env}-lock.txt; then
        ENVFILE=requirements-${env}-lock.txt
    else
        ENVFILE=requirements-${env}.txt
    fi
    echo "Found $ENVFILE, using it ..."
    export VIRTUAL_ENV=$envdir/$env
    # if environment exists, error
    if [ -d $envdir/$env ]; then
        echo "*ERROR*: $envdir/$env exists! Cannot install $env from $ENVFILE"
        exit 1
    fi
    # ensure we use the same python in jupyter so dask works
    uv venv $VIRTUAL_ENV -p $ENV_DIR/base/bin/python$PYTHON_VERSION
    # add our useful packages
    uv pip install ipykernel pip
    # uv pip is strict and sometimes fail in resolving dependencies; fall back to pip install
    uv pip install -r $ENVFILE || $VIRTUAL_ENV/bin/pip install -r $ENVFILE
    # install the kernel so jupyter can find it;
    if [ "$envdir" == "$ENV_DIR" ]; then
        uv run python -m ipykernel install --name $env --prefix $JUPYTER_DIR
        KERNEL_JSON="$JUPYTER_DIR/share/jupyter/kernels/$env/kernel.json"
        # also do the locks
        uv pip list --format=freeze > $VIRTUAL_ENV/$ENVFILE
        mkdir -p $LOCK_DIR
        cp $VIRTUAL_ENV/$ENVFILE $LOCK_DIR
        # run the following only when building the image
        if [[ "$(id -un)" == "jovyan" ]]; then
            fix-permissions $envdir/$env
        fi
    else
        uv run python -m ipykernel install --name $env --user
        KERNEL_JSON="$HOME/.local/share/jupyter/kernels/$env/kernel.json"
    fi
    # set PATH, so `!which python` works correctly in the notebook
    # set VIRTUAL_ENV so `!uv ..` works too.
    jq ".env = (.env // {}) 
        | .env.PATH = \"$envdir/$env/bin:$PATH\" 
        | .env.VIRTUAL_ENV = \"$VIRTUAL_ENV\"" $KERNEL_JSON > /tmp/tmp.$$.json
    mv /tmp/tmp.$$.json $KERNEL_JSON
    # clean up
    find $VIRTUAL_ENV -follow -type f \( -name '*.a' -o -name '*.pyc' -o -name '*.js.map' \) -delete
done

# clean
uv cache clean
$VIRTUAL_ENV/bin/pip cache purge
