name: Export software environments

on:
  # push:
  #   branches:
  #     - compact
  workflow_dispatch:
    inputs:
      images:
        description: 'Images to export: ["image-1","image-2"] or "" for all'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
        
  export-envs:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      attestations: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: do the export
        run: |
          TAG="${{ github.head_ref || github.ref_name }}" 
          python scripts/build.py --debug --no-build \
              --registry "$REGISTRY" --repository "${{ github.repository }}" \
              --tag $TAG \
              --export-envs "${{ inputs.images }}"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opt_envs.tgz
          path: ./envs_*.tgz
