name: Image Build
run-name: "Image Build: ${{ inputs.images }}"

on:
  workflow_dispatch:
    inputs:
      images:
        description: 'Images to build of the form: image-1 image-2'
        required: true
        type: string

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN`
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check links in the intro page
        uses: lycheeverse/lychee-action@v1
        with:
          args: "introduction.md"
          fail: false
      
      - name: Build and push images
        id: build-images
        run: |
          IMAGES_TO_BUILD="${{ inputs.images }}"
          TAG="${{ github.head_ref || github.ref_name }}" 
          echo "IMAGES_TO_BUILD: $IMAGES_TO_BUILD"
          echo "TAG: $TAG"

          # write variables so can be used elsewhere
          echo "IMAGES_TO_BUILD=$IMAGES_TO_BUILD" >> $GITHUB_OUTPUT
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

          if [[ "$TAG" == "main" || "$TAG" == "develop" ]]; then
            ENDPOINT="--ecr ${{ secrets.ECR_ENDPOINT }} --ecr ${{ secrets.ECR_ENDPOINT_PROD }}"
          else
            ENDPOINT="--ecr ${{ secrets.ECR_ENDPOINT }}"
          fi

          # run the build
          python scripts/build.py --debug \
              --repo "ghcr.io/${{ github.repository }}" \
              --tag $TAG \
              --build \
              --push \
              $ENDPOINT \
              $IMAGES_TO_BUILD
      
      - name: "Run image tests"
        if: "!contains(github.event.head_commit.message, '[skip-tests]')"
        run: |
          images="${{ steps.build-images.outputs.IMAGES_TO_BUILD }}"
          tag=${{ steps.build-images.outputs.TAG }}
          for image in $images; do
            echo "##### Testing ${image} #####"
            docker run -i --rm -v .:/opt/workspace/repo-code \
              "ghcr.io/${{ github.repository }}/$image:$tag" \
              bash -c "pytest -s -v /opt/workspace/repo-code/tests/test_${image//-/_}.py"
          done
  