name: Tag released images

on:
  release:
    types: [published]

jobs:

  prep-release:
    runs-on: ubuntu-latest
    
    outputs:
      images: ${{ steps.image-list.outputs.IMAGE_LIST }}

    steps:
      - name: Check the release is from main
        run: |
          if [ "${{ github.event.release.target_commitish }}" != "main" ]; then
            echo "❌ Releases must be created from main branch."
            echo "    Current ref: ${{ github.ref_name }}"
            exit 1
          fi
          echo "✅ Branch check passed."
      
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clean_storage: false
          registry_login: false
      
      - name: List images with kernels
        id: image-list
        run: |
          images=$(python scripts/build.py --kernel-images)
          IMAGES_JSON=$(jq -R -c 'split(" ")' <<< "$images")
          echo "Image List: ${IMAGES_JSON}"
          echo "IMAGE_LIST=${IMAGES_JSON}" >> $GITHUB_OUTPUT

  # Run lock export in parallel        
  export-locks:
    needs: prep-release
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
    
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.prep-release.outputs.images) }}

    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Export the locks
        run: |
          python scripts/build.py --debug \
              --repo "ghcr.io/${{ github.repository }}" \
              --tag develop \
              --export-locks \
              "${{ matrix.image }}"
            
          # pack lock files into a zip file
          if [ -d ${{ matrix.image }}_locks ]; then
            zip -r "${{ matrix.image }}-environment-locks.zip" "${{ matrix.image }}_locks"
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.image }}-environment-locks
          path: ./${{ matrix.image }}-environment-locks.zip
      
      - name: Upload lock files to the release
        uses: softprops/action-gh-release@v3
        with:
          files: ./${{ matrix.image }}-environment-locks.zip

  
  tag-images-for-release:
    needs: export-locks
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Tag main images with release tags
        run: |
          ENDPOINT="--ecr ${{ secrets.ECR_ENDPOINT }} --ecr ${{ secrets.ECR_ENDPOINT_PROD }}"
          
          # Note that all images are tagged for release
          python scripts/build.py --debug \
              --repo "ghcr.io/${{ github.repository }}" \
              --tag develop \
              --retag main stable "${{ github.event.release.tag_name }}" \
              $ENDPOINT

  tag-ami-for-release:
    needs: tag-images-for-release
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    
    steps:
      - name: Steup Environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clean_storage: false
          registry_login: false
      
      - name: python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Trigger ami release
        run: |            
          echo "++++ Copy develop AMI to stable ++++ "
          ENDPOINT="${{ secrets.AMI_ENDPOINT }} ${{ secrets.AMI_ENDPOINT_PROD }}"
          python scripts/ami-builder.py --src develop --ssm-path stable \
              --endpoint $ENDPOINT
          
          RELEASE="${{ github.event.release.tag_name }}"
          echo "++++ Copy develop AMI to release: $RELEASE ++++ "
          python scripts/ami-builder.py --src develop --ssm-path $RELEASE \
              --endpoint $ENDPOINT