name: image-tests
run-name: "Image tests: ${{ inputs.images }}"
on:
  # call from the image build pipeline
  workflow_call:
    inputs:
      images:
        required: true
        type: string
      tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      images:
        # we need json array format so we can run in a matrix
        description: 'Images of the form: image-1 image-2'
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  parse-input:
    # convert input: 'image-1 image-2' to json array to be used in matrix
    runs-on: ubuntu-latest
    outputs:
      images_json: ${{ steps.create-json.outputs.IMAGES_JSON }}
    steps:
      - name: Convert string to JSON array
        id: create-json
        run: |
          JSON_ARRAY=$(jq -R -c 'split(" ")' <<< "${{ inputs.images }}")
          echo "IMAGES_JSON=$JSON_ARRAY" >> $GITHUB_OUTPUT

  test-images:
    needs: parse-input
    runs-on: ubuntu-latest
    
    # Sets the permissions granted to the `GITHUB_TOKEN`
    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        image: ${{ fromJson(needs.parse-input.outputs.images_json) }}
  
    steps:

      - name: Checkout repository
        uses: actions/checkout@v6
  
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: "Pull Image: ${{ matrix.image }}"
        run: |
          tag=${{ inputs.tag }}
          image=${{ matrix.image }}
          docker pull ghcr.io/${{ github.repository }}/$image:$tag
          # make shorthand tag
          docker tag ghcr.io/${{ github.repository }}/$image:$tag $image

      - name: "Run image tests inside the image: ${{ matrix.image }}"
        run: |
          image=${{ matrix.image }}
          docker run -i --rm -v .:/opt/workspace/repo-code \
            $image \
            bash -c "pytest -s -v /opt/workspace/repo-code/tests/test_${image//-/_}.py"
      
      - name: "Run full notbeook tests: ${{ matrix.image }}"
        if: github.event_name == 'workflow_dispatch' && matrix.image == 'fornax-main'
        run: |
          docker run -i --rm -v .:/opt/workspace/repo-code \
            ${{ matrix.image }} \
            bash -c "pytest -s -v /opt/workspace/repo-code/tests/test_fornax_notebooks.py"
    
      - name: "Run jupyter-lab: ${{ matrix.image }}"
        run: |
          cmd="docker run -i --rm ${{ matrix.image }}"
          timeout 10 $cmd || [[ $? -eq 124 ]] && { echo "Timed out as expected."; } || exit $?
